<?php
/**
 * Sharif Judge online judge
 * @file settings.php
 * @author Mohammad Javad Naderi <mjnaderi@gmail.com>
 */
defined('BASEPATH') OR exit('No direct script access allowed');
?>

<?php $this->view('templates/top_bar'); ?>
<?php $this->view('templates/side_bar', array('selected'=>'settings')); ?>

<div id="main_container" class="scroll-wrapper">
<div class="scroll-content">

	<div id="page_title">
		<img src="<?php echo base_url('assets/images/icons/settings.png') ?>"/>
		<span><?php echo $title ?></span>
		<span class="title_menu_item">
			<a href="http://docs.sharifjudge.ir/settings" target="_blank"><i class="splashy-help"></i> Help</a>
		</span>
	</div>

	<div id="main_content">
		<p class="input_p">
		<?php if ($form_status === 'ok'): ?>
			<div class="shj_ok">Settings updated successfully.</div>
		<?php elseif ($form_status === 'error'): ?>
			<div class="shj_error">Error updating settings.</div>
		<?php endif ?>
		<?php foreach ($errors as $error): ?>
			<div class="shj_error"><?php echo $error ?></div>
		<?php endforeach ?>
		<?php if ($defc === FALSE): ?>
			<div class="shj_error">"Tester path" is not correct.</div>
		<?php endif ?>
		</p>
		<?php echo form_open('settings/update') ?>
			<p class="input_p">
				<label for="form_timezone">
					Timezone<br>
					<a target="_blank" href="http://www.php.net/manual/en/timezones.php">list of timezones</a>
				</label>
				<span class="form_comment timer"></span><br>
				<input id="form_timezone" type="text" name="timezone" class="sharif_input medium" value="<?php echo $tz ?>"/>
				<?php echo form_error('timezone','<div class="shj_error">','</div>'); ?>
			</p>
			<p class="input_p">
				<label for="form_week">Week Start Day</label>
				<select id="form_week" name="week_start" class="sharif_input">
					<option value="0" <?php if($week_start==0) echo 'selected="selected"' ?>>Sunday</option>
					<option value="1" <?php if($week_start==1) echo 'selected="selected"' ?>>Monday</option>
					<option value="2" <?php if($week_start==2) echo 'selected="selected"' ?>>Tuesday</option>
					<option value="3" <?php if($week_start==3) echo 'selected="selected"' ?>>Wednesday</option>
					<option value="4" <?php if($week_start==4) echo 'selected="selected"' ?>>Thursday</option>
					<option value="5" <?php if($week_start==5) echo 'selected="selected"' ?>>Friday</option>
					<option value="6" <?php if($week_start==6) echo 'selected="selected"' ?>>Saturday</option>
				</select>
			</p>
			<p class="input_p">
				<label for="form_t_path">Full Path to <code>tester</code></label>
				<input id="form_t_path" type="text" name="tester_path" class="sharif_input medium" value="<?php echo $tester_path ?>"/>
			</p>
			<p class="input_p">
				<label for="form_a_path">Full Path to <code>assignments</code></label>
				<input id="form_a_path" type="text" name="assignments_root" class="sharif_input medium" value="<?php echo $assignments_root ?>"/>
			</p>
			<p class="input_p">
				<label for="form_up_limit">Upload Size Limit (kB)</label>
				<input id="form_up_limit" type="text" name="file_size_limit" class="sharif_input medium" value="<?php echo $file_size_limit ?>"/>
				<?php echo form_error('file_size_limit','<div class="shj_error">','</div>'); ?>
			</p>
			<p class="input_p">
				<label for="form_out_limit">Output Size Limit (kB)</label>
				<input id="form_out_limit" type="text" name="output_size_limit" class="sharif_input medium" value="<?php echo $output_size_limit ?>"/><br>
				<span class="form_comment clear">Sets a limit for size of output file generated by submitted code</span>
				<?php echo form_error('output_size_limit','<div class="shj_error">','</div>'); ?>
			</p>
			<p class="input_p">
				<label for="form_rpp_all">Results Per Page</label>
				<input id="form_rpp_all" type="text" name="rpp_all" class="sharif_input medium" value="<?php echo $results_per_page_all ?>"/>
				<p class="form_comment clear">In "All Submissions"<br>Enter 0 for no limit</p>
				<?php echo form_error('results_per_page_all','<div class="shj_error">','</div>'); ?>
			</p>
			<p class="input_p">
				<label for="form_rpp_final">Results Per Page</label>
				<input id="form_rpp_final" type="text" name="rpp_final" class="sharif_input medium" value="<?php echo $results_per_page_final ?>"/>
				<p class="form_comment clear">In "Final Submissions"<br>Enter 0 for no limit</p>
				<?php echo form_error('results_per_page_final','<div class="shj_error">','</div>'); ?>
			</p>
			<p class="input_p">
				<input id="form_en_reg" type="checkbox" name="enable_registration" value="1" <?php if ($enable_registration) echo 'checked' ?>/>
				<label for="form_en_reg">Registration</label><br>
				<span class="form_comment">Open Public Registration.</span>
			</p>
			<p class="input_p">
				<label for="form_reg_code">Registration Code</label>
				<input id="form_reg_code" type="text" name="registration_code" class="sharif_input medium" value="<?php echo $registration_code ?>"/><br>
				<p class="form_comment clear">If you want to enable registration (above option), It is better to give a registration code<br>
					to students in your class for validating registration. Enter 0 to disable.</p>
				<?php echo form_error('registration_code','<div class="shj_error">','</div>'); ?>
			</p>
			<p class="input_p">
				<input id="form_log" type="checkbox" name="enable_log" value="1" <?php if ($enable_log) echo 'checked' ?>/>
				<label for="form_log">Log</label><br>
				<span class="form_comment">Enable Log</span>
			</p>
			<p class="input_p">
				<label for="form_late_rule">Default Coefficient Rule</label>
				<span class="form_comment clear">PHP script without &lt;?php ?&gt; tags</span><br>
				<textarea id="form_late_rule" name="default_late_rule" rows="15" class="sharif_input add_text clear"><?php echo $default_late_rule ?></textarea>
			</p>

			<h2 class="shj_form">Email</h2>

			<p class="input_p">
				<label for="form_mail_from">Send Emails From</label>
				<input id="form_mail_from" type="text" name="mail_from" class="sharif_input medium" value="<?php echo $mail_from ?>"/>
				<?php echo form_error('mail_from','<div class="shj_error">','</div>'); ?>
			</p>
			<p class="input_p">
				<label for="form_mail_name">Send Emails "From" Name</label>
				<input id="form_mail_name" type="text" name="mail_from_name" class="sharif_input medium" value="<?php echo $mail_from_name ?>"/>
				<?php echo form_error('mail_from_name','<div class="shj_error">','</div>'); ?>
			</p>
			<p class="input_p">
				<label for="form_mail_reset">Password Reset Email</label>
				<span class="form_comment">You can use {SITE_URL}, {RESET_LINK} and {VALID_TIME}</span><br>
				<textarea id="form_mail_reset" name="reset_password_mail" rows="15" class="sharif_input add_text clear"><?php echo $reset_password_mail ?></textarea>
			</p>
			<p class="input_p">
				<label for="form_mail_add">Add User Email</label>
				<span class="form_comment clear">You can use {SITE_URL}, {LOGIN_URL}, {ROLE}, {USERNAME} and {PASSWORD}</span><br>
				<textarea id="form_mail_add" name="add_user_mail" rows="15" class="sharif_input add_text clear"><?php echo $add_user_mail ?></textarea>
			</p>


			<h2 class="shj_form">Sandboxing <span class="title_menu_item"><a href="http://docs.sharifjudge.ir/sandboxing" target="_blank"><i class="splashy-help"></i> Help</a></span></h2>

			<p class="input_p">
				<input id="form_easysandbox" type="checkbox" name="enable_easysandbox" value="1" <?php if ($enable_easysandbox) echo 'checked' ?>/>
				<label for="form_easysandbox">EasySandbox</label>
			</p>
			<p class="form_comment">Enable EasySandbox for C/C++.<br>
				You must <a href="http://docs.sharifjudge.ir/sandboxing#build_easysandbox" target="_blank">build EasySandbox</a> before enabling it.<br>
				<?php if (!$sandbox_built): ?>
					<span style="color: red;">You have not built EasySandbox yet.</span>
				<?php endif ?>
			</p>

			<p class="input_p">
				<input id="form_java_policy" type="checkbox" name="enable_java_policy" value="1" <?php if ($enable_java_policy) echo 'checked' ?>/>
				<label for="form_java_policy">Java Policy</label>
			</p>
			<p class="form_comment">
				Enable <a href="http://docs.sharifjudge.ir/sandboxing#java_sandboxing" target="_blank">Java Sandboxing</a>
			</p>



			<h2 class="shj_form">Shield <span class="title_menu_item"><a href="http://docs.sharifjudge.ir/shield" target="_blank"><i class="splashy-help"></i> Help</a></span></h2>

			<p class="input_p">
				<input id="form_c_sh" type="checkbox" name="enable_c_shield" value="1" <?php if ($enable_c_shield) echo 'checked' ?>/> <label for="form_c_sh">C Shield</label><br>
				<span class="form_comment">Enable <a href="http://docs.sharifjudge.ir/shield" target="_blank">Shield</a> for C</span>
			</p>
			<p class="input_p">
				<input id="form_cpp_sh" type="checkbox" name="enable_cpp_shield" value="1" <?php if ($enable_cpp_shield) echo 'checked' ?>/> <label for="form_cpp_sh">C++ Shield</label><br>
				<span class="form_comment">Enable <a href="http://docs.sharifjudge.ir/shield" target="_blank">Shield</a> for C++</span>
			</p>
			<p class="input_p">
				<input id="form_py2_sh" type="checkbox" name="enable_py2_shield" value="1" <?php if ($enable_py2_shield) echo 'checked' ?>/> <label for="form_py2_sh">Python 2 Shield</label><br>
				<span class="form_comment">Enable <a href="http://docs.sharifjudge.ir/shield" target="_blank">Shield</a> for Python 2</span>
			</p>
			<p class="input_p">
				<input id="form_py3_sh" type="checkbox" name="enable_py3_shield" value="1" <?php if ($enable_py3_shield) echo 'checked' ?>/> <label for="form_py3_sh">Python 3 Shield</label><br>
				<span class="form_comment">Enable <a href="http://docs.sharifjudge.ir/shield" target="_blank">Shield</a> for Python 3</span>
			</p>
			<p class="input_p">
				<label for="form_def_c">Shield Rules (for C)</label>
				<textarea id="form_def_c" name="def_c" rows="15" class="sharif_input add_text clear"><?php if($defc!==FALSE) echo $defc ?></textarea>
			</p>
			<p class="input_p">
				<label for="form_def_cpp">Shield Rules (for C++)</label>
				<textarea id="form_def_cpp" name="def_cpp" rows="15" class="sharif_input add_text clear"><?php if($defcpp!==FALSE) echo $defcpp ?></textarea>
			</p>
			<p class="input_p">
				<label for="form_shield_py2">Shield (for Python 2)</label>
				<textarea id="form_shield_py2" name="shield_py2" rows="15" class="sharif_input add_text clear"><?php if($shield_py2!==FALSE) echo $shield_py2 ?></textarea>
			</p>
			<p class="input_p">
				<label for="form_shield_py3">Shield (for Python 3)</label>
				<textarea id="form_shield_py3" name="shield_py3" rows="15" class="sharif_input add_text clear"><?php if($shield_py3!==FALSE) echo $shield_py3 ?></textarea>
			</p>
			<p class="input_p">
				<br>
				<input type="submit" value="Save Changes" class="sharif_input"/>
			</p>
		</form>

	</div> <!-- main_content -->
</div> <!-- scroll-content -->
</div> <!-- main_container -->